name: release

env:
  GITHUB_REGISTRY: "ghcr.io/jokay/ccu-historian"
  GITLAB_REGISTRY: "registry.gitlab.com/jokay/docker-ccu-historian"
  DOCKERHUB_REGISTRY: "docker.io/xjokay/ccu-historian"
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x"

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  registries:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "CREATED=$(date -u +%Y-%m-%dT%H:%M:%S%z)" >> "${GITHUB_ENV}"
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "${GITHUB_ENV}"
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # renovate: tag=v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0
      - name: Cache Docker layers
        uses: actions/cache@4b0cf6cc4619e737324ddfcec08fff2413359514 # tag=v3.0.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Login to GitLab Container Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1.14.1
        with:
          registry: registry.gitlab.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITLAB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1.14.1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # tag=v2.10.0
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.created=${{ env.CREATED }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.documentation=${{ github.event.repository.html_url }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ env.VERSION }}
          tags: |
            ${{ env.GITHUB_REGISTRY }}:latest
            ${{ env.GITHUB_REGISTRY }}:${{ env.VERSION }}
            ${{ env.GITLAB_REGISTRY }}:latest
            ${{ env.GITLAB_REGISTRY }}:${{ env.VERSION }}
            ${{ env.DOCKERHUB_REGISTRY }}:latest
            ${{ env.DOCKERHUB_REGISTRY }}:${{ env.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  create:
    needs:
      - registries
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "CREATED=$(date -u +%Y-%m-%dT%H:%M:%S%z)" >> "${GITHUB_ENV}"
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "${GITHUB_ENV}"
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: Create release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # renovate: tag=v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
