name: release

env:
  GITHUB_REGISTRY: "ghcr.io/jokay/ccu-historian"
  GITLAB_REGISTRY: "registry.gitlab.com/jokay/docker-ccu-historian"
  DOCKERHUB_REGISTRY: "docker.io/xjokay/ccu-historian"
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x"

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  registries:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "CREATED=$(date -u +%Y-%m-%dT%H:%M:%S%z)" >> "${GITHUB_ENV}"
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "${GITHUB_ENV}"
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0
      - name: Cache Docker layers
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # tag=v3.0.10
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Login to GitLab Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2.0.0
        with:
          registry: registry.gitlab.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITLAB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.created=${{ env.CREATED }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.documentation=${{ github.event.repository.html_url }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ env.VERSION }}
          tags: |
            ${{ env.GITHUB_REGISTRY }}:latest
            ${{ env.GITHUB_REGISTRY }}:${{ env.VERSION }}
            ${{ env.GITLAB_REGISTRY }}:latest
            ${{ env.GITLAB_REGISTRY }}:${{ env.VERSION }}
            ${{ env.DOCKERHUB_REGISTRY }}:latest
            ${{ env.DOCKERHUB_REGISTRY }}:${{ env.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  create:
    needs:
      - registries
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "CREATED=$(date -u +%Y-%m-%dT%H:%M:%S%z)" >> "${GITHUB_ENV}"
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "${GITHUB_ENV}"
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Create release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # tag=v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
